apiVersion: v1
kind: Namespace
metadata:
  name: knative-control-plane
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: authorization-service
  namespace: knative-control-plane
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1" # Ensures at least one instance is running
    spec:
      containers:
      - image: 192.168.222.3:32000/authorization-service:v1
        ports:
        - containerPort: 8080
        env:
          - name: ETCD_ENDPOINTS
            value: "http://your-etcd-cluster-client-service:2379"
          - name: ETCD_DIAL_TIMEOUT
            value: "5s"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
      imagePullSecrets:
      - name: regcred