apiVersion: batch/v1
kind: Job
metadata:
  name: data-migration-job
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
        - name: migration
          image: busybox
          command: ["sh", "-c", "echo Running data migration; sleep 5"]
      restartPolicy: Never
