apiVersion: v1
kind: Namespace
metadata:
  name: knative-control-plane
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data
  namespace: knative-control-plane
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: knative-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:latest
          ports:
            - containerPort: 2379
          command:
            - /usr/local/bin/etcd
          args:
            - --name knative-control-plane
            - --data-dir /etcd-data
            - --listen-client-urls http://0.0.0.0:2379
            - --advertise-client-urls http://0.0.0.0:2379
            # - --auth-token=simple
          volumeMounts:
            - name: etcd-data
              mountPath: /etcd-data
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: etcd-data
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: knative-control-plane
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
  clusterIP: None # Makes it a headless service
